# Generated by Django 3.2.11 on 2022-01-16 22:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
