# Generated by Django 3.2.11 on 2022-01-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_module_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
