# Generated by Django 3.2.11 on 2022-01-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_answer_question_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_percentage',
            field=models.IntegerField(default=70),
        ),
    ]
