# Generated by Django 3.2.11 on 2022-01-17 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220117_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
